config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "grams#index"
  resources :grams do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gram
    belongs_to :model
end

app/models/gram.rb
class Gram < ActiveRecord::Base
    validates :message, presence: true
    validates :picture, presence: true
    has_many :comments
    
    mount_uploader :picture, PictureUploader

    belongs_to :model
    
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :grams
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController< ActionController::Base 
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
  
    def render_not_found(status=:not_found)
        render plain: "#{status.to_s.titleize} :(", status: status
      end
    

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_model!, only: [:create]
    def create
        @gram = Gram.find_by_id(params[:gram_id])
        return render_not_found if @gram.blank?
        @gram.comments.create(comment_params.merge(model: current_model))
        redirect_to root_path
      end
    
      private

   
 
    
      def comment_params
        params.require(:comment).permit(:message)
      end
end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
    before_action :authenticate_model!, only: [:new, :create, :edit, :update, :destroy]
    def index
      @grams = Gram.all
    end
    
    def new
      @gram = Gram.new
    end

    def create
      @gram = current_model.grams.create(gram_params)
      if @gram.valid?
        redirect_to root_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def show
      
      @gram = Gram.find_by_id(params[:id])
      return render_not_found if @gram.blank? 
    end

    def edit
      @gram = Gram.find_by_id(params[:id])
      return render_not_found if @gram.blank?
      return render_not_found(:forbidden) if @gram.model != current_model
      end

      def update
        @gram = Gram.find_by_id(params[:id])
          return render_not_found if @gram.blank?
          return render_not_found(:forbidden) if @gram.model != current_model
        
        @gram.update_attributes(gram_params)
        if @gram.valid?
          redirect_to root_path
        else
            return render :edit, status: :unprocessable_entity
        end 
      end

      def destroy
        @gram = Gram.find_by_id(params[:id])
        return render_not_found if @gram.blank?
        return render_not_found(:forbidden) if @gram.model != current_model
         @gram.destroy
        redirect_to root_path
      end

    private

    def gram_params
        params.require(:gram).permit(:message, :picture)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/edit.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
  <h2>Edit Gram</h2>

<%= simple_form_for @gram do |f| %>
  <%= f.input :message %>
  <%= f.input :picture %>
  <%= f.submit 'Update', class: 'my-btn' %>
<% end %>

</div>

app/views/grams/index.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
  <% @grams.each do |gram| %>
  <div class="card">
    <div class="handle"><%= gram.model.email %></div>
    <%= image_tag gram.picture_url, class: 'img-fluid' %>
    <p>
      <%= gram.message %>
    </p>
      <div class="gram-actions float-right">
      <% if current_model && current_model == gram.model %>
        <%= link_to 'Edit', edit_gram_path(gram) %>
         <%= link_to 'Destroy', gram_path(gram), method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    </div>
    <br class="clear-fix" />
      <div class="comments">
      <h3>Comments</h3>
       <% gram.comments.each do |comment| %>
          <div class="comment">
            <span class="comment_handle">
              <%= comment.model.email %>
            </span>

            <%= comment.message %>
          </div>
        <% end %>

      <h4>Add a comment</h4>
      <%= simple_form_for Comment.new, url: gram_comments_path(gram) do |f| %>
        <%= f.input :message %>
        <%= f.submit 'Add Comment', class: 'my-btn' %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/grams/new.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
<h1>New Gram</h1>

 <%= simple_form_for @gram do |f| %>
  <%= f.input :picture %>
  <%= f.input :message %>
  <%= f.submit "Post!", class: 'my-btn' %>
<% end %>

</div>

app/views/grams/show.html.erb
<%= @gram.inspect %>
<% @gram.picture.each do |photo| %>
     
        <%= image_tag picture.picture.url,class: "col-3" %>
      
        <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grammable</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
     <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,100,300,600,700' rel='stylesheet' type='text/css'>
</head>  
  </head>

  <body>
  <div class="top-nav">
  <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
    <div class="brand float-left">
      Grammable
    </div>
    <div class="add float-right">
  <% if current_model %>
      You're signed in as <%= current_model.email %>.
      <%= link_to "New Post", new_gram_path %>
      <%= link_to "Sign out", destroy_model_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_model_session_path %>
      <%= link_to "Sign Up", new_model_registration_path %>
    <% end %>
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/models/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/models/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>